version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: "Verify"
          command: go mod verify
      - run:
          name: "Build"
          command: |
            curl -sfL -o /tmp/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.9.1/protoc-3.9.1-linux-x86_64.zip && sudo unzip /tmp/protoc.zip -d /usr/local/
            go get -u github.com/golang/protobuf/protoc-gen-go
            go generate ./...
            go build ./cmd/...
      - run:
          name: "Lint"
          command: |
            GO111MODULE=off go get gopkg.in/golangci/golangci-lint.v1/cmd/golangci-lint
            golangci-lint run
      - run:
          name: "Vet"
          command: go vet ./...
      - run:
          name: "Test"
          command: go test -v -coverprofile=c.out -race ./...

      - codecov/upload:
          file: "./c.out"

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
